# Generated by Django 6.1 on 2026-09-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendardate',
            new_name='gtfs_calend_service_11472c_idx',
            old_name='gtfs_calenda_servic_8aa0cc_idx',
        ),
        migrations.RenameIndex(
            model_name='route',
            new_name='gtfs_routes_route_l_49c826_idx',
            old_name='gtfs_routes_route_l_8a71ce_idx',
        ),
        migrations.RenameIndex(
            model_name='route',
            new_name='gtfs_routes_route_t_68440d_idx',
            old_name='gtfs_routes_route_t_4f13f5_idx',
        ),
        migrations.RenameIndex(
            model_name='stop',
            new_name='gtfs_stops_stop_na_617605_idx',
            old_name='gtfs_stops_stop_nam_0a1f32_idx',
        ),
        migrations.RenameIndex(
            model_name='stop',
            new_name='gtfs_stops_parent__e6f243_idx',
            old_name='gtfs_stops_parent__6dbf91_idx',
        ),
        migrations.RenameIndex(
            model_name='stop',
            new_name='gtfs_stops_locatio_a8e768_idx',
            old_name='gtfs_stops_locatio_6a05e7_idx',
        ),
        migrations.RenameIndex(
            model_name='stoptime',
            new_name='gtfs_stop_t_trip_id_252095_idx',
            old_name='gtfs_stop_ti_trip_i_5c0b7a_idx',
        ),
        migrations.RenameIndex(
            model_name='stoptime',
            new_name='gtfs_stop_t_stop_id_2b57d7_idx',
            old_name='gtfs_stop_ti_stop_i_9fbb4d_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='gtfs_transf_from_st_df4bd2_idx',
            old_name='gtfs_transf_from_st_9e6db6_idx',
        ),
        migrations.RenameIndex(
            model_name='transfer',
            new_name='gtfs_transf_to_stop_748763_idx',
            old_name='gtfs_transf_to_stop__d8d0d7_idx',
        ),
        migrations.RenameIndex(
            model_name='trip',
            new_name='gtfs_trips_route_i_c009dd_idx',
            old_name='gtfs_trips_route_i_3f3ce4_idx',
        ),
        migrations.RenameIndex(
            model_name='trip',
            new_name='gtfs_trips_service_b63104_idx',
            old_name='gtfs_trips_service_6f8b54_idx',
        ),
        migrations.AlterField(
            model_name='route',
            name='route_short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_headsign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
